name: Deploy PostgreSQL to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy PostgreSQL to Kubernetes
        run: |
          kubectl apply -f kubernetes/postgres-deployment.yaml
          kubectl apply -f kubernetes/postgres-service.yaml
          kubectl apply -f kubernetes/postgres-pvc.yaml  # Si estás usando PVC para persistencia

      - name: Verify PostgreSQL Pod status
        run: |
          kubectl get pods -l app=postgres

  state:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy PostgreSQL to Kubernetes
        run: |
          kubectl apply -f kubernetes/postgres-statefulset.yaml
          kubectl apply -f kubernetes/postgres-service.yaml

      - name: Verify PostgreSQL Pod status
        run: |
          kubectl get pods -l app=postgres
